services:
  ralloc:
    container_name: ralloc
    build:
      context: ../
      dockerfile: .docker/prod.Dockerfile
    env_file:
      - ../.env.production
      - ../.env.local
    restart: always
    ports:
      - 3000:3000
    networks:
      - ralloc_net
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:8-alpine
    container_name: ralloc-redis
    restart: always
    # ports:
    #  - "6379:6379"
    volumes:
      - ./ralloc_redis_data:/data
      - ../redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ralloc_net

networks:
  ralloc_net:
    external: true

volumes:
  ralloc_redis_data:
    driver: local
