services:
  ralloc-dev:
    container_name: ralloc-dev
    build:
      context: ../
      dockerfile: .docker/dev.Dockerfile
    env_file:
      - ../.env.development
      - ../.env.local
    volumes:
      - ../src:/app/src
      - ../public:/app/public
    # restart: unless-stopped
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    networks:
      - ralloc_net
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:8-alpine
    container_name: ralloc-dev-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    # restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - ./ralloc_redis_data_dev:/data
      - ../redis.dev.conf:/usr/local/etc/redis/redis.conf
    networks:
      - ralloc_net


networks:
  ralloc_net:
    external: true


volumes:
  ralloc_redis_data_dev:
    driver: local