services:
  ralloc-dev:
    container_name: ralloc-dev
    build:
      context: ../
      dockerfile: .docker/web.dev.Dockerfile
    env_file:
      - ../apps/web/.env.development
      - ../apps/web/.env.local
      - ../apps/ws/.env.development
      - ../packages/core/.env.development
    volumes:
      - ../apps/web/src:/app/apps/web/src
      - ../apps/web/public:/app/apps/web/public
      - ../packages/core/src:/app/packages/core/src
    # restart: unless-stopped
    environment:
      - PORT=3001
      - FORCE_COLOR=1
    ports:
      - 3001:3001
    networks:
      - ralloc_net
    depends_on:
      redis:
        condition: service_started
  
  ralloc-ws-dev:
    container_name: ralloc-ws-dev
    build:
      context: ../
      dockerfile: .docker/ws.dev.Dockerfile
    env_file:
      - ../packages/core/.env.development
      - ../apps/ws/.env.development
      - ../apps/web/.env.local
    environment:
      - NODE_ENV=development
    volumes: 
      - ../apps/ws/src:/app/apps/ws/src
      - ../packages/core/src:/app/packages/core/src
    ports:
      - 6767:6767
    networks:
      - ralloc_net
    depends_on: 
      - redis

  redis:
    image: redis:8-alpine
    container_name: ralloc-dev-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    # restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - ./ralloc_redis_data_dev:/data
      - ../redis.dev.conf:/usr/local/etc/redis/redis.conf
    networks:
      - ralloc_net


networks:
  ralloc_net:
    external: true


volumes:
  ralloc_redis_data_dev:
    driver: local